name: Force Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Confirm Ruby version
        run: ruby -v
